### ISSUE TITLE
Does Not Work

### ISSUE THREAD

**Issue by Optimaximal** [WEEDO3DTECH/PrusaSlicer-Profiles#1]
Unless I'm mistaken, these profiles do not work, even if you add a [Vendor] block, as per https://github.com/prusa3d/PrusaSlicer/wiki/Vendor-bundles-and-updating-process

**Comment by WinstonMao** [comment]
> Unless I'm mistaken, these profiles do not work, even if you add a [Vendor] block, as per
This profile is a config bundle profile exported by PrusaSlicer. Just import it in the PrusaSlicer：

![HowToImportProfile](https://user-images.githubusercontent.com/8135506/222027522-6187d8e6-e6a8-4b62-a17a-44e340cededc.png)

**Comment by Optimaximal** [comment]
Ok, apologies, I'm new to Prusa and assumed added the printer to the setup wizard!
